name = "proxy-worker"
main = "worker/src/index.js"
compatibility_date = "2025-01-01"
account_id = "7a4081a2d83d3f43fe6b1be1c926fd1c"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "PROXIES"
id = "35adf28c6d4c4a5d9d6c8440611f6efa"

[site]
bucket = "worker/public"
