name = "proxy-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"
account_id = "7a4081a2d83d3f43fe6b1be1c926fd1c"

# 静态资源配置 - 使用更明确的格式
[site]
bucket = "./public"

# 定时任务，每10分钟执行一次
[triggers]
crons = ["*/10 * * * *"]

# KV 命名空间绑定
[[kv_namespaces]]
binding = "proxyworker"
id = "35adf28c6d4c4a5d9d6c8440611f6efa"
preview_id = "35adf28c6d4c4a5d9d6c8440611f6efa"