name = "proxy-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"
account_id = "7a4081a2d83d3f43fe6b1be1c926fd1c"

# 发布静态站点的目录
site = { bucket = "./public" }

# 定时任务，每5分钟触发一次
[triggers]
crons = ["*/5 * * * *"]

# KV 命名空间绑定，用于存储代理列表
[[kv_namespaces]]
binding = "PROXIES"
id = "35adf28c6d4c4a5d9d6c8440611f6efa"

# KV 命名空间绑定，用于存储静态资源
[[kv_namespaces]]
binding = "__STATIC_CONTENT"
id = "<请替换为静态资源命名空间 ID>"