name: Update proxies

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate proxies.json
        run: |
          python update_proxies.py

      - name: Commit proxies.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add public/proxies.json
          git commit -m "Update proxies.json" || echo "No changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 